import IISAvtomatizaciya_zakupok_gotovayaОтчетОЗакEController from '../i-i-s-avtomatizaciya-zakupok-gotovaya-отчет-о-зак-e';

var IISAvtomatizaciya_zakupok_gotovayaОтчетОЗакENewController = IISAvtomatizaciya_zakupok_gotovayaОтчетОЗакEController;
export default IISAvtomatizaciya_zakupok_gotovayaОтчетОЗакENewController;
