import IISAvtomatizaciya_zakupok_gotovayaНоменклатураEController from '../i-i-s-avtomatizaciya-zakupok-gotovaya-номенклатура-e';

var IISAvtomatizaciya_zakupok_gotovayaНоменклатураENewController = IISAvtomatizaciya_zakupok_gotovayaНоменклатураEController;
export default IISAvtomatizaciya_zakupok_gotovayaНоменклатураENewController;
